name = "cthead"
description = ""
raw_file = "cthead.raw"

[resolution]
x = 256
y = 256
z = 113

[voxel]
sample_type = "unsigned short"
endianness = "big"
    [voxel.size]
    x = 1.0
    y = 1.0
    z = 2.0
    unit = ""
