name = "engine"
description = ""
raw_file = "engine.raw"

[resolution]
x = 149
y = 208
z = 110

[voxel]
sample_type = "unsigned char"
endianness = "little"
    [voxel.size]
    x = 1.0
    y = 1.0
    z = 1.0
    unit = ""
